analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.6469534
  brandColors:
    - '#ffbb00'
    - '#feecb6'
    - '#c55800'
    - '#82010e'
    - '#d39349'
  rhythmicContrast: 0.75
typography_spectrum: 0.4749104
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5215054
favicon: null
name: karimjoreige
